### ISSUE TITLE
Error pas salah masukkan ID

### ISSUE THREAD

**Issue by nurjavier8789** [DaddyAzizi/UKL2-Lelang#2]
error ketika setelah user input ID Penawar selain yang disediakan, informasi penawarannya error.
kayaknya error di arraynya deh 🤔

error yang sama ketika setelah input ID barang selain yang disediakan, tiba tiba sama kayak yang diatas errornya

**Comment by DaddyAzizi** [comment]
dah

**Comment by nurjavier8789** [comment]
woke banh
